version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pg_doctor_booking
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doctor_booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/doctor_booking
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  pgdata: